#
# Copyright (C) 2023-2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/oneplus/udon
BOARD_VENDOR := oneplus

# Build System Lenient Flags for Custom ROMs
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_BUILD_MODULES := true
BUILD_BROKEN_VENDOR_PROPERTY_NAMESPACE := true
BUILD_BROKEN_INCORRECT_PARTITION_IMAGES := true

# Include the common OEM chipset BoardConfig (Snapdragon 8+ Gen 1, SM8475 / taro).
#
# NOTE: device/oneplus/sm8450-common does NOT exist -- the LineageOS repo of
# that name is an empty placeholder. Do not re-add an include for it.
include device/oneplus/sm8475-common/BoardConfigCommon.mk

# Display
TARGET_SCREEN_DENSITY := 450

# Recovery
TARGET_RECOVERY_UI_MARGIN_HEIGHT := 103

# Security patch level
#
# NOTE: must match the OxygenOS build the vendor blobs were extracted from.
VENDOR_SECURITY_PATCH := 2026-07-01
BOOT_SECURITY_PATCH := 2026-07-01

# Fingerprint (under-display optical FOD)
SOONG_CONFIG_NAMESPACES += ONEPLUS_FOD
SOONG_CONFIG_ONEPLUS_FOD += POS_X POS_Y SIZE
SOONG_CONFIG_ONEPLUS_FOD_POS_X := 445
SOONG_CONFIG_ONEPLUS_FOD_POS_Y := 2200
SOONG_CONFIG_ONEPLUS_FOD_SIZE := 190

# Properties
TARGET_ODM_PROP += $(DEVICE_PATH)/odm.prop
TARGET_PRODUCT_PROP += $(DEVICE_PATH)/product.prop
TARGET_SYSTEM_EXT_PROP += $(DEVICE_PATH)/system_ext.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Inherit proprietary vendor BoardConfig.
#
# Generated by ./extract-files.sh from a CPH2487 OxygenOS dump; not checked in.
-include vendor/oneplus/udon/BoardConfigVendor.mk
