#!/usr/bin/env python3
"""
Generate a PixelOS local manifest for OnePlus 11R (udon / CPH2487).

Why this exists
---------------
PixelOS is AOSP based: its manifest does *not* ship the Qualcomm CAF HALs
(hardware/qcom-caf/...), the qcom sepolicy vendor tree or vendor/qcom/opensource/*.
The udon device tree + sm8450-common tree are LineageOS style and need all of
those, so a local manifest has to supply them.

This script pulls the exact qcom/CAF project set out of the LineageOS manifest
for a given branch (lineage-23.2 = Android 16, lineage-24.0 = Android 17) and
merges it with the pinned udon device / vendor / kernel / hardware repositories
that are known to build for this device.

Usage
-----
    python3 gen_local_manifest.py --android 16 [-o pixelos-udon-sixteen.xml]
    python3 gen_local_manifest.py --android 17 [-o pixelos-udon-seventeen.xml]

Requires: python3 + network access to api.github.com (or pass --offline with a
previously downloaded --cache-dir).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.request

LOS_MANIFEST_REPO = "LineageOS/android"
LOS_FILES = ["default.xml", "snippets/lineage.xml"]

# Android version -> LineageOS branch that carries the matching CAF HALs
ANDROID_TO_LOS = {
    "16": "lineage-23.2",
    "17": "lineage-24.0",
}
# Android version -> PixelOS manifest branch
ANDROID_TO_PIXELOS = {
    "16": "sixteen",
    "17": "seventeen",
}

# LineageOS manifest entries we copy over (path prefixes). Everything else in
# the LineageOS manifest is already provided (in some form) by PixelOS.
CAF_PATH_PREFIXES = (
    "device/qcom/sepolicy_vndr/sm8450",
    "hardware/qcom-caf/bootctrl",
    "hardware/qcom-caf/thermal",
    "hardware/qcom-caf/wlan",
    "hardware/qcom-caf/sm8450/",
    "vendor/qcom/opensource/",
)
# sm8450-6.6 is the 6.6-kernel flavour; udon uses the 5.10/6.1 sm8450 stack.
CAF_PATH_EXCLUDE = (
    # 6.6-kernel flavour; udon uses the sm8450 (5.10/6.1) stack
    "hardware/qcom-caf/sm8450-6.6/",
    # these two are replaced by the udon-patched forks pinned above
    "hardware/qcom-caf/common",
    "hardware/qcom-caf/sm8450/audio/agm",
)

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  PixelOS {pixelos_branch} (Android {android}) local manifest for OnePlus 11R (udon / CPH2487).

  Generated by crave/manifests/gen_local_manifest.py - do not hand-edit,
  regenerate instead (or copy it and edit the copy).

  Layout:
    * udon device / vendor / kernel trees  - pinned, known-good for this device
    * hardware/qcom-caf + vendor/qcom      - taken from the LineageOS {los_branch}
                                             manifest (PixelOS is AOSP based and
                                             does not ship any CAF HALs)

  Drop it in as .repo/local_manifests/udon.xml
-->
<manifest>
  <remote name="los"      fetch="https://github.com/" />
  <remote name="rocko"    fetch="https://github.com/rocko5498" />
  <remote name="pjgowtham" fetch="https://github.com/pjgowtham" />
  <remote name="arman"    fetch="https://github.com/Arman-ATI" />
  <remote name="icecold"  fetch="https://github.com/ICECOLD90191" />

  <!-- ===================== udon device / common ===================== -->
  <project path="device/oneplus/udon"
           name="android_device_oneplus_udon"
           remote="rocko" revision="{udon_device_rev}" />
  <project path="device/oneplus/sm8450-common"
           name="android_device_oneplus_sm8450-common"
           remote="rocko" revision="{common_rev}" />

  <!-- ===================== proprietary blobs ======================== -->
  <project path="vendor/oneplus/udon"
           name="android_vendor_oneplus_udon"
           remote="rocko" revision="{udon_vendor_rev}" />
  <project path="vendor/oneplus/sm8450-common"
           name="proprietary_vendor_oneplus_sm8450-common"
           remote="rocko" revision="{common_vendor_rev}" />

  <!-- ============================ kernel ============================ -->
  <project path="kernel/oneplus/sm8450"
           name="android_kernel_oneplus_sm8450"
           remote="rocko" revision="{kernel_rev}" />
  <project path="kernel/oneplus/sm8450-modules"
           name="android_kernel_oneplus_sm8450-modules"
           remote="pjgowtham" revision="{kernel_rev}" />
  <project path="kernel/oneplus/sm8450-devicetrees"
           name="android_kernel_oneplus_sm8450-devicetrees"
           remote="pjgowtham" revision="{kernel_rev}" />

  <!-- ==================== OnePlus / Dolby hardware ================== -->
  <project path="hardware/oplus"
           name="android_hardware_oplus"
           remote="arman" revision="{oplus_rev}" />
  <project path="hardware/dolby"
           name="hardware_dolby"
           remote="icecold" revision="{dolby_rev}" />

  <!-- ========= udon-patched CAF trees (replace the LOS ones) ======== -->
  <project path="hardware/qcom-caf/common"
           name="android_hardware_qcom-caf_common"
           remote="rocko" revision="{caf_common_rev}" />
  <project path="hardware/qcom-caf/sm8450/audio/agm"
           name="android_vendor_qcom_opensource_agm"
           remote="rocko" revision="{agm_rev}" />
"""

FOOTER = """
  <!--
    hardware/qcom-caf/common above ships os_pickup linkfiles. When a
    stale copy is left behind by an earlier sync the build picks up the wrong
    Android.mk; the resync step in build-pixelos-udon.sh cleans those.
  -->
</manifest>
"""

# Pinned revisions of the udon trees. These follow the LineageOS 23.2 (A16)
# bring-up, which is the newest set that is known to build for this device.
UDON_REVS = {
    "16": dict(
        udon_device_rev="fresh-udon-20260727",
        common_rev="lineage-23.2",
        udon_vendor_rev="fresh-udon-20260727",
        common_vendor_rev="lineage-23.2",
        kernel_rev="lineage-23.2",
        oplus_rev="lineage-23.2",
        dolby_rev="A16",
        caf_common_rev="lineage-23.2-udon-audio-namespace",
        agm_rev="lineage-23.2-caf-sm8450-udon-acdb",
    ),
    # Android 17: the device/HAL/kernel trees have no A17 port yet, so we stay
    # on the same pinned udon trees and only move the CAF HALs to lineage-24.0.
    "17": dict(
        udon_device_rev="fresh-udon-20260727",
        common_rev="lineage-24.0",
        udon_vendor_rev="fresh-udon-20260727",
        common_vendor_rev="lineage-23.2",
        kernel_rev="lineage-23.2",
        oplus_rev="lineage-23.2",
        dolby_rev="A16",
        caf_common_rev="lineage-23.2-udon-audio-namespace",
        agm_rev="lineage-23.2-caf-sm8450-udon-acdb",
    ),
}


def github_raw(owner_repo: str, path: str, ref: str, token: str | None = None) -> str:
    url = f"https://api.github.com/repos/{owner_repo}/contents/{path}?ref={ref}"
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github.raw",
            "User-Agent": "udon-pixelos-manifest-generator",
        }
        | ({"Authorization": f"Bearer {token}"} if token else {}),
    )
    with urllib.request.urlopen(req, timeout=60) as fh:
        return fh.read().decode("utf-8", "replace")


def load_los_manifest(branch: str, cache_dir: str | None, token: str | None) -> str:
    parts = []
    for path in LOS_FILES:
        cache_file = None
        if cache_dir:
            os.makedirs(cache_dir, exist_ok=True)
            cache_file = os.path.join(cache_dir, f"{branch}__{path.replace('/', '_')}")
            if os.path.exists(cache_file):
                parts.append(open(cache_file).read())
                continue
        data = github_raw(LOS_MANIFEST_REPO, path, branch, token)
        if cache_file:
            with open(cache_file, "w") as fh:
                fh.write(data)
        parts.append(data)
    return "\n".join(parts)


PROJECT_RE = re.compile(r"<project\b[\s\S]*?/>|<project\b[\s\S]*?</project>")


def default_revision(manifest_xml: str) -> str:
    # Revision a project inherits when it does not set its own.

    m = re.search(r'<default\b[^>]*revision="([^"]+)"', manifest_xml)
    if not m:
        return "UNSET"
    return m.group(1).replace("refs/heads/", "").replace("refs/tags/", "")


def extract_caf_projects(manifest_xml: str) -> list[str]:
    out = []
    for entry in PROJECT_RE.findall(manifest_xml):
        m = re.search(r'path="([^"]+)"', entry)
        if not m:
            continue
        path = m.group(1)
        if any(path.startswith(p) for p in CAF_PATH_EXCLUDE):
            continue
        if not any(path.startswith(p) for p in CAF_PATH_PREFIXES):
            continue
        # normalise: one attribute per line, drop groups (otherwise `repo sync`
        # skips them) and point the remote at our own "los" remote
        name = re.search(r'name="([^"]+)"', entry).group(1)
        rev = re.search(r'revision="([^"]+)"', entry)
        revision = rev.group(1) if rev else None
        if revision is None:
            # inherits the manifest default revision
            revision = default_revision(manifest_xml)
        out.append((path, name, revision))
    out.sort()
    return out


def render(android: str, los_xml: str) -> str:
    los_branch = ANDROID_TO_LOS[android]
    pixelos_branch = ANDROID_TO_PIXELOS[android]
    body = [HEADER.format(android=android, pixelos_branch=pixelos_branch,
                          los_branch=los_branch, **UDON_REVS[android])]

    body.append("\n  <!-- ======== CAF HALs / qcom vendor trees from LineageOS "
                f"{los_branch} ======== -->\n")
    for path, name, revision in extract_caf_projects(los_xml):
        body.append(
            f'  <project path="{path}"\n'
            f'           name="{name}"\n'
            f'           remote="los" revision="{revision}" />\n'
        )
    body.append(FOOTER)
    return "".join(body)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--android", choices=sorted(ANDROID_TO_LOS), default="16",
                    help="Android version of the PixelOS branch (16 = sixteen, 17 = seventeen)")
    ap.add_argument("-o", "--output", default=None)
    ap.add_argument("--cache-dir", default=None, help="cache/serve LOS manifest XML here")
    ap.add_argument("--offline", action="store_true", help="only use --cache-dir, never network")
    ap.add_argument("--token", default=os.environ.get("GITHUB_TOKEN"))
    args = ap.parse_args()

    if args.offline and not args.cache_dir:
        ap.error("--offline requires --cache-dir")

    if args.cache_dir and args.offline:
        los_xml = ""
        for path in LOS_FILES:
            cache_file = os.path.join(args.cache_dir, f"{ANDROID_TO_LOS[args.android]}__{path.replace('/', '_')}")
            if not os.path.exists(cache_file):
                ap.error(f"cache miss (offline): {cache_file}")
            los_xml += open(cache_file).read()
    else:
        los_xml = load_los_manifest(ANDROID_TO_LOS[args.android], args.cache_dir, args.token)

    text = render(args.android, los_xml)
    out = args.output or f"pixelos-udon-{ANDROID_TO_PIXELOS[args.android]}.xml"
    with open(out, "w") as fh:
        fh.write(text)
    print(f"wrote {out} ({len(text)} bytes, "
          f"{len(extract_caf_projects(los_xml))} LineageOS CAF projects)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
